databases:
  - name: practica-db
    plan: free
    databaseName: practica
    user: practica_user

services:
  - type: web
    name: practica-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: practica-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: practica-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: practica-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: practica-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: practica-db
          property: password
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
