databases:
  - name: pedido-db
    plan: free
    databaseName: dbpedidos
    user: dbuser

services:
  - type: web
    name: pedido-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8081
      - key: DATABASE_URL
        fromDatabase:
          name: pedido-db
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: pedido-db
          property: user
      - key: DATABASE_PASS
        fromDatabase:
          name: pedido-db
          property: password
      - key: DDL_AUTO
        value: update
      - key: SHOW_SQL
        value: false
