services:
  - type: web
    name: pedido-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: pedido-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pedido-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: pedido-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: pedido-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pedido-db
          property: password
      - key: PORT
        value: 10000

databases:
  - name: pedido-db
    plan: free
    databaseName: pedido
    user: pedido_user